#!/bin/bash
echo ""
echo "================================================"
echo "   Browser-Cache löschen"
echo "================================================"
echo ""
echo "WICHTIG: Führen Sie folgende Schritte aus:"
echo ""
echo "1. Browser öffnen (Chrome, Firefox, Safari)"
echo "2. Drücken Sie:"
echo "   - Mac: CMD + SHIFT + DELETE"
echo "   - Linux: CTRL + SHIFT + DELETE"
echo "3. Wählen Sie: 'Gesamter Zeitraum'"
echo "4. Haken bei:"
echo "   - Cookies"
echo "   - Cache"
echo "5. 'Daten löschen' klicken"
echo ""
echo "ODER einfacher:"
echo ""
echo "1. Browser öffnen: http://localhost:5000"
echo "2. Drücken Sie:"
echo "   - Mac: CMD + SHIFT + R"
echo "   - Linux: CTRL + SHIFT + R"
echo ""
echo "Danach sollte oben links 'v2.1.0' stehen!"
echo ""
